name: Fetch WorkInfo

on:
  schedule:
    - cron: '0 15 * * *'  # KST로 자정마다 실행
  workflow_dispatch:  # 수동으로 실행할 수 있는 옵션

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch data
        run: |
          # 오늘 날짜와 다음 주 날짜 계산
          today=$(date +%Y-%m-%d)
          next_week=$(date -d "+7 days" +%Y-%m-%d)
          next_two_week=$(date -d "+14 days" +%Y-%m-%d)
          next_three_week=$(date -d "+21 days" +%Y-%m-%d)

          # 오늘 날짜 데이터
          curl -o _data/schedule_c1_svc_today.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$today"
          curl -o _data/schedule_c1_epc_today.json "http://35.209.216.133:5000/ASCH?ymod=C1%EA%B5%90%ED%99%98&ydate=$today"
          curl -o _data/schedule_c1_etc_today.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%83%81%ED%99%A9&ydate=$today"
          curl -o _data/schedule_c2_svc_today.json "http://35.209.216.133:5000/ASCH?ymod=C2%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$today"
          curl -o _data/schedule_c2_epc_today.json "http://35.209.216.133:5000/ASCH?ymod=C2%EA%B5%90%ED%99%98&ydate=$today"

          # 다음 주 날짜 데이터
          curl -o _data/schedule_c1_svc_next_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$next_week"
          curl -o _data/schedule_c1_epc_next_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EA%B5%90%ED%99%98&ydate=$next_week"
          curl -o _data/schedule_c1_etc_next_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%83%81%ED%99%A9&ydate=$next_week"
          curl -o _data/schedule_c2_svc_next_week.json "http://35.209.216.133:5000/ASCH?ymod=C2%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$next_week"
          curl -o _data/schedule_c2_epc_next_week.json "http://35.209.216.133:5000/ASCH?ymod=C2%EA%B5%90%ED%99%98&ydate=$next_week"
          
          # 다다음 주 날짜 데이터
          curl -o _data/schedule_c1_svc_next_two_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$next_two_week"
          curl -o _data/schedule_c1_epc_next_two_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EA%B5%90%ED%99%98&ydate=$next_two_week"          
          curl -o _data/schedule_c1_etc_next_two_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%83%81%ED%99%A9&ydate=$next_two_week"
          curl -o _data/schedule_c2_svc_next_two_week.json "http://35.209.216.133:5000/ASCH?ymod=C2%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$next_two_week"
          curl -o _data/schedule_c2_epc_next_two_week.json "http://35.209.216.133:5000/ASCH?ymod=C2%EA%B5%90%ED%99%98&ydate=$next_two_week"
          
          # 다다다음 주 날짜 데이터
          curl -o _data/schedule_c1_svc_next_three_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$next_three_week"
          curl -o _data/schedule_c1_epc_next_three_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EA%B5%90%ED%99%98&ydate=$next_three_week"
          curl -o _data/schedule_c1_etc_next_three_week.json "http://35.209.216.133:5000/ASCH?ymod=C1%EC%83%81%ED%99%A9&ydate=$next_three_week"
          curl -o _data/schedule_c2_svc_next_three_week.json "http://35.209.216.133:5000/ASCH?ymod=C2%EC%84%9C%EB%B9%84%EC%8A%A4&ydate=$next_three_week"
          curl -o _data/schedule_c2_epc_next_three_week.json "http://35.209.216.133:5000/ASCH?ymod=C2%EA%B5%90%ED%99%98&ydate=$next_three_week"
          

      - name: Commit and push changes
        run: |
          git config --local user.name "yunkwangyou"
          git config --local user.email "yunkwangyou@github.com"
          
          git add _data/schedule_c1_svc_today.json
          git add _data/schedule_c1_epc_today.json
          git add _data/schedule_c1_etc_today.json
          git add _data/schedule_c2_svc_today.json
          git add _data/schedule_c2_epc_today.json

          git add _data/schedule_c1_svc_next_week.json
          git add _data/schedule_c1_epc_next_week.json
          git add _data/schedule_c1_etc_next_week.json
          git add _data/schedule_c2_svc_next_week.json
          git add _data/schedule_c2_epc_next_week.json
          
          git add _data/schedule_c1_svc_next_two_week.json
          git add _data/schedule_c1_epc_next_two_week.json
          git add _data/schedule_c1_etc_next_two_week.json
          git add _data/schedule_c2_svc_next_two_week.json
          git add _data/schedule_c2_epc_next_two_week.json
          
          git add _data/schedule_c1_svc_next_three_week.json
          git add _data/schedule_c1_epc_next_three_week.json
          git add _data/schedule_c1_etc_next_three_week.json
          git add _data/schedule_c2_svc_next_three_week.json
          git add _data/schedule_c2_epc_next_three_week.json
          
          git commit -m "Update schedule data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}